### ISSUE TITLE
app\blueprint\views

### ISSUE THREAD

**Issue by 20142995** [ody5sey/Voyager#1]
![image](https://user-images.githubusercontent.com/38929533/74751202-de406680-52a7-11ea-9799-5f9a2bb7e859.png)

**Comment by ody5sey** [comment]
是发现bug了吗??

**Comment by 20142995** [comment]
端口扫描下载结果时报错，没有start和end键值，create_date和end_time么



发自我的小米手机在 ody5sey <notifications@github.com>，2020年2月21日 上午7:35写道：是发现bug了吗??



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ody5sey/Voyager/issues/1?email_source=notifications\u0026email_token=AJJAI7J22YAL37TEOUAX2MLRD4HVDA5CNFSM4KXG72NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMQ3BGA#issuecomment-589410456",

"url": "https://github.com/ody5sey/Voyager/issues/1?email_source=notifications\u0026email_token=AJJAI7J22YAL37TEOUAX2MLRD4HVDA5CNFSM4KXG72NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMQ3BGA#issuecomment-589410456",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ody5sey** [comment]
麻烦贴图

**Comment by ody5sey** [comment]
是的， 已修复
